development:
  adapter: postgresql
  database: accq_dev
  encoding: utf8
  host: localhost
  username: <%=ENV['DB_USER']%>
  password: <%=ENV['DB_PASS']%>

test:
  adapter: postgresql
  database: accq_test
  encoding: utf8
  host: localhost
  username: <%=ENV['DB_USER']%>
  password: <%=ENV['DB_PASS']%>

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  encoding: unicode
  pool: 5

staging:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  encoding: unicode
  pool: 5
